#include <tyos.h>

void __attribute__((fastcall, naked)) jogo()
{
__asm__ volatile
( 
  "        mov   $0x00, %%ah           ;" 
  "        mov   $0x13, %%al           ;" 
  "        int $0x10                   ;"

  "        movw   $0xa000, %%cx         ;"
  "        movw   %%cx, %%es            ;"
  "        mov    $0x0, %%si            ;"
  "        mov    $0x00, %%bx           ;"
  "        mov    $0x0a, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;"

  " fundo_azul1:                         "
  "        mov    $0x35, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0x3200, %%si          ;"
  "        jne fundo_azul1              ;"

  " fundo_azul2:                         "
  "        mov    $0x4d, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0x8340, %%si          ;"
  "        jne fundo_azul2              ;"

  " fundo_azul3:                         "
  "        mov    $0x4c, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0xd480, %%si          ;"
  "        jne fundo_azul3              ;"

  " grama:                                "
  "        mov    $0x02, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0xe100, %%si          ;"
  "        jne grama                    ;"

  " chao:                                "
  "        mov    $0xbb, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0xfa00, %%si          ;"
  "        jne chao                     ;"


  "        mov    $0x528, %%si          ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x532, %%cx          ;" 
  " nuvem1_a:                            "
  "        mov    $0x0f, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem1_a                 ;"
  "        inc    %%dx                  ;"
  "        add    $310,  %%si           ;"
  "        add    $320,  %%cx           ;" 
  "        cmp    $0x05, %%dx           ;"
  "        jne nuvem1_a                 ;"

  "        mov    $0xb5e, %%si          ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0xb7c, %%cx          ;" 
  " nuvem1_b:                            "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem1_b                 ;"
  "        inc    %%dx                  ;"
  "        add    $290,  %%si           ;"
  "        add    $320,  %%cx           ;"
  "        cmp    $0x07, %%dx           ;"
  "        jne nuvem1_b                 ;"

  "        mov    $0x1414, %%si         ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x1446, %%cx         ;" 
  " nuvem1_c:                            "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem1_c                 ;"
  "        inc    %%dx                  ;"
  "        add    $270,  %%si           ;"
  "        add    $320,  %%cx           ;"
  "        cmp    $0x0a, %%dx           ;"
  "        jne nuvem1_c                 ;"

  "        mov    $0x120c, %%si         ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x1216, %%cx         ;" 
  " nuvem2_a:                             "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem2_a                 ;"
  "        inc    %%dx                  ;"
  "        add    $310,  %%si           ;"
  "        add    $320,  %%cx           ;" 
  "        cmp    $0x05, %%dx           ;"
  "        jne nuvem2_a                 ;"

  "        mov    $0x1842, %%si         ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x1860, %%cx         ;" 
  " nuvem2_b:                            "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem2_b                 ;"
  "        inc    %%dx                  ;"
  "        add    $290,  %%si           ;"
  "        add    $320,  %%cx           ;" 
  "        cmp    $0x07, %%dx           ;"
  "        jne nuvem2_b                 ;"

  "        mov    $0x20f8, %%si         ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x212a, %%cx         ;" 
  " nuvem2_c:                            "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem2_c                 ;"
  "        inc    %%dx                  ;"
  "        add    $270,  %%si           ;"
  "        add    $320,  %%cx           ;"
  "        cmp    $0x0a, %%dx           ;"
  "        jne nuvem2_c                 ;"

  

  "        ret                         ;" 
  :
  :
  : "bx", "cx", "dx", "si","ax"

 );
}