#include <tyos.h>

void __attribute__((fastcall, naked)) jogo()
{
__asm__ volatile
( 
  "        mov   $0x00, %%ah           ;" 
  "        mov   $0x13, %%al           ;" 
  "        int $0x10                   ;"

  "        movw   $0xa000, %%cx         ;"
  "        movw   %%cx, %%es            ;"
  "        mov    $0x0, %%si            ;"
  "        mov    $0x00, %%bx           ;"
  "        mov    $0x0a, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;"

  " fundo_azul1:                         "
  "        mov    $0x35, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0x3200, %%si          ;"
  "        jne fundo_azul1              ;"

  " fundo_azul2:                         "
  "        mov    $0x4d, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0x8340, %%si          ;"
  "        jne fundo_azul2              ;"

  " fundo_azul3:                         "
  "        mov    $0x4c, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0xd480, %%si          ;"
  "        jne fundo_azul3              ;"

  " grama:                                "
  "        mov    $0x02, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0xe100, %%si          ;"
  "        jne grama                    ;"

  " chao:                                "
  "        mov    $0xbb, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;" 
  "        inc    %%si                  ;"
  "        cmp   $0xfa00, %%si          ;"
  "        jne chao                     ;"


  "        mov    $0x528, %%si          ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x532, %%cx          ;" 
  " nuvem1_a:                            "
  "        mov    $0x0f, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem1_a                 ;"
  "        inc    %%dx                  ;"
  "        add    $310,  %%si           ;"
  "        add    $320,  %%cx           ;" 
  "        cmp    $0x05, %%dx           ;"
  "        jne nuvem1_a                 ;"

  "        mov    $0xb5e, %%si          ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0xb7c, %%cx          ;" 
  " nuvem1_b:                            "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem1_b                 ;"
  "        inc    %%dx                  ;"
  "        add    $290,  %%si           ;"
  "        add    $320,  %%cx           ;"
  "        cmp    $0x07, %%dx           ;"
  "        jne nuvem1_b                 ;"

  "        mov    $0x1414, %%si         ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x1446, %%cx         ;" 
  " nuvem1_c:                            "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem1_c                 ;"
  "        inc    %%dx                  ;"
  "        add    $270,  %%si           ;"
  "        add    $320,  %%cx           ;"
  "        cmp    $0x0a, %%dx           ;"
  "        jne nuvem1_c                 ;"

  "        mov    $0x120c, %%si         ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x1216, %%cx         ;" 
  " nuvem2_a:                             "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem2_a                 ;"
  "        inc    %%dx                  ;"
  "        add    $310,  %%si           ;"
  "        add    $320,  %%cx           ;" 
  "        cmp    $0x05, %%dx           ;"
  "        jne nuvem2_a                 ;"

  "        mov    $0x1842, %%si         ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x1860, %%cx         ;" 
  " nuvem2_b:                            "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem2_b                 ;"
  "        inc    %%dx                  ;"
  "        add    $290,  %%si           ;"
  "        add    $320,  %%cx           ;" 
  "        cmp    $0x07, %%dx           ;"
  "        jne nuvem2_b                 ;"

  "        mov    $0x20f8, %%si         ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0x212a, %%cx         ;" 
  " nuvem2_c:                            "
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne nuvem2_c                 ;"
  "        inc    %%dx                  ;"
  "        add    $270,  %%si           ;"
  "        add    $320,  %%cx           ;"
  "        cmp    $0x0a, %%dx           ;"
  "        jne nuvem2_c                 ;"

  "        mov    $0xb55e, %%si         ;"
  "        mov    $0x00, %%dx           ;"
  "        mov    $0xb577, %%cx         ;" 
  " personagem:                          "
  "        mov    $0x26, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%si                  ;"
  "        cmp   %%cx, %%si             ;"
  "        jne personagem               ;"
  "        inc    %%dx                  ;"
  "        add    $295,  %%si           ;"
  "        add    $320,  %%cx           ;"
  "        cmp    $0x19, %%dx           ;"
  "        jne personagem               ;"

  "        mov    $0x00, %%dx           ;"
  " inicio:                              "
  "        mov    $0xb67f, %%si         ;"
  "        mov    $0xb67f, %%cx         ;"

  " obst_nascendo:                       "
  "        mov    $0x01, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        inc    %%dl                  ;"
  "        add    $320,  %%si           ;"
  "        cmp    $0x19, %%dl           ;"
  "        jne obst_nascendo            ;"
  "        jmp sleep                    ;"

  " obst_morrendo:                       "
  "        add    $25,  %%si            ;"
  "        mov    $0x4c, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        sub    $25,  %%si            ;"
  "        inc    %%dl                  ;"
  "        add    $320,  %%si           ;"
  "        cmp    $0x19, %%dl           ;"
  "        jne obst_morrendo             ;"
  "        jmp sleep                    ;"


  " obst_andando:                       "
  "        mov    $0x01, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        add    $25,  %%si            ;"
  "        mov    $0x4c, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%si) ;"
  "        sub    $25,  %%si            ;"
  "        inc    %%dl                  ;"
  "        add    $320,  %%si           ;"
  "        cmp    $0x19, %%dl           ;"
  "        jne obst_andando             ;"
  "        jmp sleep                    ;"

  " tecla_apertada:                      "
  "        mov    $0x00, %%ah           ;"
  "        int    $0x16                 ;"
  "        mov    $0x0, %%ah            ;"
  "        mov    $0xd35e, %%di         ;"
  " salto_a:                             " 
  "        mov    $0x4c, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%di) ;"
  "        inc    %%ah                  ;"
  "        inc    %%di                  ;"
  "        cmp    $25, %%ah             ;"
  "        jne  salto_a                 ;"
  "        mov    $0x0, %%ah            ;"
  " salto_b:                             " 
  "        mov    $0x26, %%al           ;"
  "        sub    $8025,  %%di         ;"
  "        movb %%al, %%es:(%%bx, %%di) ;"
  "        add    $8025,  %%di          ;"
  "        inc    %%ah                  ;"
  "        inc    %%di                  ;"
  "        cmp    $25, %%ah             ;"
  "        jne  salto_b                 ;"
  "        jmp salto                    ;"
  " subindo:                             "
  "        sub    $370, %%di            ;"
  "        mov    $0x00, %%ah           ;"
  "        jmp salto_a                  ;"

  " queda_a:                             " 
  "        mov    $0x26, %%al           ;"
  "        movb %%al, %%es:(%%bx, %%di) ;"
  "        inc    %%ah                  ;"
  "        inc    %%di                  ;"
  "        cmp    $25, %%ah             ;"
  "        jne  queda_a                 ;"
  "        mov    $0x0, %%ah            ;"
  " queda_b:                             " 
  "        mov    $0x4c, %%al           ;"
  "        sub    $8025,  %%di         ;"
  "        movb %%al, %%es:(%%bx, %%di) ;"
  "        add    $8025,  %%di          ;"
  "        inc    %%ah                  ;"
  "        inc    %%di                  ;"
  "        cmp    $25, %%ah             ;"
  "        jne  queda_b                 ;"
  "        jmp salto                    ;"
  " descendo:                            "
  "        add    $270, %%di            ;"
  "        mov    $0x00, %%ah           ;"
  "        jmp queda_a                  ;"
  " descer:                              "
  "        sub    $50, %%di             ;"
  "        jmp queda_a                  ;"

  " sleep:                               "
  "        mov    $0x00, %%dh           ;"
  "        mov    $0x01, %%ah           ;"
  "        int    $0x16                 ;"
  "        lahf                         ;"
  "        cmp    $0x28, %%ah           ;"
  "        jbe   tecla_apertada         ;"
  " tecla_nao_apertada:                  "
  "        mov    %%cx, %%bx            ;"
  "        mov    $0x0, %%cx            ;"
  "        mov    $0xff0, %%dx          ;"
  "        mov    $0x86, %%ah           ;"
  "        int    $0x15                 ;"
  "        mov    %%bx, %%cx            ;"
  "        mov    $0x0, %%bx            ;"
  "        dec    %%cx                  ;"
  "        mov    %%cx, %%si            ;"
  "        mov    $0x00, %%dl           ;"
  "        cmp    $0xb527, %%cx         ;"
  "        je  inicio                   ;"
  "        cmp    $0xb540, %%cx         ;"
  "        jbe obst_morrendo            ;"  
  "        cmp    $0xb666, %%cx         ;"
  "        jbe obst_andando             ;" 
  "        jmp obst_nascendo            ;"

  " salto:                               "
  "        inc    %%dh                  ;"
  "        cmp    $77, %%dh             ;"
  "        jg  sleep                    ;"

  "        mov    %%cx, %%bx            ;"
  "        mov    $0x0, %%cx            ;"
  "        mov    %%dh, %%al            ;"
  "        mov    $0xff0, %%dx          ;"
  "        mov    $0x86, %%ah           ;"
  "        int    $0x15                 ;"

  "        mov    %%bx, %%cx            ;"
  "        mov    $0x0, %%bx            ;"
  "        mov    %%al, %%dh            ;"
  "        cmp    $39, %%dh             ;"
  "        jb   subindo                 ;"

  "        mov    $0x00, %%ah           ;"
  "        cmp    $39, %%dh             ;"
  "        je  descer                   ;"

  "        cmp    $39, %%dh             ;"
  "        jg  descendo                 ;"

  " salto_cont:                          "
  "        dec    %%cx                  ;"
  "        mov    %%cx, %%si            ;"
  "        mov    $0x00, %%dl           ;"
  "        cmp    $0xb527, %%cx         ;"
  "        je  inicio                   ;"
  "        cmp    $0xb540, %%cx         ;"
  "        jbe obst_morrendo            ;"  
  "        cmp    $0xb666, %%cx         ;"
  "        jbe obst_andando             ;" 
  "        jmp obst_nascendo            ;"



  "        ret                          ;" 
  :
  :
  : "bx", "cx", "dx", "si","ax"

 );
}

/* "        cmp    $0xb577, %%cx         ;"  */